[serve.static]
plugins = ["./bunPluginTailwind.ts"]

# Allows client-side code to consume environment variables. During the build,
# these env vars will be replaced with static values.
env = "BUN_PUBLIC_*"
